site_name: Ligato Docs
site_url: https://docs.ligato.io/
site_description: Ligato documentation
site_author: Ligato Team

repo_url: https://github.com/ligato/docs

theme:
  name: rtd-dropdown
  custom_dir: custom/
  highlightjs: true
  hljs_languages:
    - go
    - yaml
    - sh

extra_css:
  - css/extra.css

nav:
  - INTRODUCTION:
    - Agent: intro/agent.md
    - Overview: intro/overview.md
    - Glossary: intro/glossary.md
  - USER GUIDE:
    - Get Agent: user-guide/get-agent.md
    - Quickstart Guide: user-guide/quickstart.md
    - Reference: user-guide/reference.md
    - Concepts: user-guide/concepts.md
    - ARM64: user-guide/arm64.md
    - FAQ: user-guide/faq.md
  - TUTORIALS:
    - Hello World: tutorials/01_hello-world.md
    - Plugin Dependencies: tutorials/02_plugin-deps.md
    - REST Handler: tutorials/03_rest-handler.md
    - KV Datastore: tutorials/04_kv-store.md
    - KV Scheduler: tutorials/05_kv-scheduler.md
    - Plugin Lookup: tutorials/06_plugin-lookup.md
    - VPP Connection: tutorials/07_vpp-connection.md
    - GRPC Handler: tutorials/08_grpc-tutorial.md
  - PLUGINS:
    - Plugin Overview: plugins/plugin-overview.md
    - Core VPP Plugins: plugins/core-vpp-plugins.md
    - Other VPP Plugins: plugins/other-vpp-plugins.md
    - Linux Plugins: plugins/linux-plugins.md
    - Connection Plugins: plugins/connection-plugins.md
    - Database Plugins: plugins/db-plugins.md
    - Infra Plugins: plugins/infra-plugins.md
  - DEVELOPER GUIDE:
    - Plugin Lookup: developer-guide/plugin-lookup.md
    - KV Scheduler: developer-guide/kvscheduler.md
    - KV Descriptors: developer-guide/kvdescriptor.md
    - Control Flows: developer-guide/control-flows.md
    - Go Docs: developer-guide/godocs.md
  - TESTING:
    - Integration Tests: testing/integration-tests.md
    - Robot Framework Guide: testing/robot-framework-guide.md
  - TOOLS:
    - VPP-Agent-Ctl: tools/vpp-agent-ctl.md
  - TROUBLESHOOTING:
    - KVS Troubleshooting: troubleshooting/kvs-troubleshooting.md

markdown_extensions:
  - extra
  - admonition
  - smarty
#  - codehilite Note: disabled for now since it breaks code fences, will be re-enabled later
  - def_list
  - toc:
      permalink: 

